-- MySQL Script generated by MySQL Workbench
-- Mon Dec 22 22:49:32 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Habitat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Habitat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Habitat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Habitat` ;

-- -----------------------------------------------------
-- Table `Habitat`.`Elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Elementos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `dataNasc` DATE NULL,
  `escolaridade` VARCHAR(75) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `parentesco` VARCHAR(45) NULL,
  `ocupacao` VARCHAR(45) NULL,
  `naturalidade` VARCHAR(45) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `familia` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Elementos_Familias1_idx` (`familia` ASC),
  CONSTRAINT `fk_Elementos_Familias1`
    FOREIGN KEY (`familia`)
    REFERENCES `Habitat`.`Familias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Funcionarios` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `nome` VARCHAR(75) NULL,
  `NIF` VARCHAR(45) NULL,
  `rua` VARCHAR(75) NULL,
  `localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Familias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Familias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rendimento` DECIMAL(10,2) NULL,
  `rua` VARCHAR(75) NULL,
  `localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  `contacto` VARCHAR(75) NULL,
  `responsavel` INT NULL,
  `funcionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Familias_Elementos_idx` (`responsavel` ASC),
  INDEX `fk_Familias_Funcionarios1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_Familias_Elementos`
    FOREIGN KEY (`responsavel`)
    REFERENCES `Habitat`.`Elementos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Familias_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `Habitat`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Candidaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Candidaturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataAbertura` DATE NULL,
  `dataDecisao` DATE NULL,
  `observacoes` VARCHAR(75) NULL,
  `estado` VARCHAR(45) NULL,
  `funcionario` VARCHAR(45) NOT NULL,
  `familia` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Candidaturas_Funcionarios1_idx` (`funcionario` ASC),
  INDEX `fk_Candidaturas_Familias1_idx` (`familia` ASC),
  CONSTRAINT `fk_Candidaturas_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `Habitat`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidaturas_Familias1`
    FOREIGN KEY (`familia`)
    REFERENCES `Habitat`.`Familias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Projectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Projectos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `candidatura` INT NOT NULL,
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `descricao` VARCHAR(75) NULL,
  `orcamento` DECIMAL(10,2) NULL,
  `funcionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `candidatura`),
  INDEX `fk_Projectos_Funcionarios1_idx` (`funcionario` ASC),
  INDEX `fk_Projectos_Candidaturas1_idx` (`candidatura` ASC),
  CONSTRAINT `fk_Projectos_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `Habitat`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projectos_Candidaturas1`
    FOREIGN KEY (`candidatura`)
    REFERENCES `Habitat`.`Candidaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Tarefas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`ProjectoTarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`ProjectoTarefas` (
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  `projecto` INT NOT NULL,
  `tarefas` INT NOT NULL,
  PRIMARY KEY (`projecto`, `tarefas`),
  CONSTRAINT `fk_ProjectoTarefas_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `Habitat`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoTarefas_Tarefas1`
    FOREIGN KEY (`tarefas`)
    REFERENCES `Habitat`.`Tarefas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Voluntarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL,
  `dataAssociacao` DATE NULL,
  `tipo` VARCHAR(45) NULL,
  `contacto` VARCHAR(75) NULL,
  `dataNascimento` DATE NULL,
  `profissao` VARCHAR(45) NULL,
  `rua` VARCHAR(75) NULL,
  `localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  `nomeEquipa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`ProjectoTarefaVoluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`ProjectoTarefaVoluntario` (
  `duracaoHoras` INT NULL,
  `dataRealizacao` DATE NULL,
  `voluntarios` INT NOT NULL,
  `tarefas` INT NOT NULL,
  `projecto` INT NOT NULL,
  PRIMARY KEY (`voluntarios`, `tarefas`, `projecto`),
  INDEX `fk_ProjectoTarefaVoluntario_Tarefas1_idx` (`tarefas` ASC),
  INDEX `fk_ProjectoTarefaVoluntario_Projectos1_idx` (`projecto` ASC),
  CONSTRAINT `fk_ProjectoTarefaVoluntario_Voluntarios1`
    FOREIGN KEY (`voluntarios`)
    REFERENCES `Habitat`.`Voluntarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoTarefaVoluntario_Tarefas1`
    FOREIGN KEY (`tarefas`)
    REFERENCES `Habitat`.`Tarefas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoTarefaVoluntario_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `Habitat`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Doadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Doadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL,
  `NIF` VARCHAR(45) NULL,
  `rua` VARCHAR(75) NULL,
  `Localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  `contacto` VARCHAR(75) NULL,
  `dataAssociacao` DATE NULL,
  `actividade` VARCHAR(45) NULL,
  `email` VARCHAR(75) NULL,
  `site` VARCHAR(75) NULL,
  `pessoaDeContacto` VARCHAR(75) NULL,
  `voluntario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Doadores_Voluntarios1_idx` (`voluntario` ASC),
  CONSTRAINT `fk_Doadores_Voluntarios1`
    FOREIGN KEY (`voluntario`)
    REFERENCES `Habitat`.`Voluntarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `nrParticipantes` INT NULL,
  `observacoes` VARCHAR(75) NULL,
  `funcionario` VARCHAR(45) NULL,
  `projecto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Eventos_Funcionarios1_idx` (`funcionario` ASC),
  INDEX `fk_Eventos_Projectos1_idx` (`projecto` ASC),
  CONSTRAINT `fk_Eventos_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `Habitat`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `Habitat`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Doacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(75) NULL,
  `data` DATE NULL,
  `tipo` VARCHAR(45) NULL,
  `valor` DECIMAL(10,2) NULL,
  `quantidade` INT NULL,
  `unidade` VARCHAR(45) NULL,
  `doador` INT NOT NULL,
  `evento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Doacoes_Doadores1_idx` (`doador` ASC),
  INDEX `fk_Doacoes_Eventos1_idx` (`evento` ASC),
  CONSTRAINT `fk_Doacoes_Doadores1`
    FOREIGN KEY (`doador`)
    REFERENCES `Habitat`.`Doadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doacoes_Eventos1`
    FOREIGN KEY (`evento`)
    REFERENCES `Habitat`.`Eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(75) NULL,
  `quantidade` INT NULL,
  `unidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`ProjectoMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`ProjectoMaterial` (
  `quantidade` INT NULL,
  `material` INT NOT NULL,
  `projecto` INT NOT NULL,
  PRIMARY KEY (`material`, `projecto`),
  INDEX `fk_ProjectoMaterial_Projectos1_idx` (`projecto` ASC),
  CONSTRAINT `fk_ProjectoMaterial_Material1`
    FOREIGN KEY (`material`)
    REFERENCES `Habitat`.`Material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoMaterial_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `Habitat`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Anexos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Anexos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `anexo` BLOB NULL,
  `Familias_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Anexos_Familias1_idx` (`Familias_id` ASC),
  CONSTRAINT `fk_Anexos_Familias1`
    FOREIGN KEY (`Familias_id`)
    REFERENCES `Habitat`.`Familias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`Perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`Perguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(256) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Habitat`.`CandidaturaPerguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Habitat`.`CandidaturaPerguntas` (
  `resposta` VARCHAR(256) NULL,
  `Candidaturas_id` INT NOT NULL,
  `Perguntas_id` INT NOT NULL,
  PRIMARY KEY (`Candidaturas_id`, `Perguntas_id`),
  INDEX `fk_CandidaturaPerguntas_Perguntas1_idx` (`Perguntas_id` ASC),
  CONSTRAINT `fk_CandidaturaPerguntas_Candidaturas1`
    FOREIGN KEY (`Candidaturas_id`)
    REFERENCES `Habitat`.`Candidaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CandidaturaPerguntas_Perguntas1`
    FOREIGN KEY (`Perguntas_id`)
    REFERENCES `Habitat`.`Perguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
