-- MySQL Script generated by MySQL Workbench
-- Sat Dec 13 20:34:16 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Elementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Elementos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `dataNasc` DATE NULL,
  `escolaridade` VARCHAR(75) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `parentesco` VARCHAR(45) NULL,
  `ocupacao` VARCHAR(45) NULL,
  `naturalidade` VARCHAR(45) NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `familia` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Elementos_Familias1_idx` (`familia` ASC),
  CONSTRAINT `fk_Elementos_Familias1`
    FOREIGN KEY (`familia`)
    REFERENCES `mydb`.`Familias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `nome` VARCHAR(75) NULL,
  `NIF` VARCHAR(45) NULL,
  `rua` VARCHAR(75) NULL,
  `localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Familias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Familias` (
  `id` INT NOT NULL,
  `rendimento` DECIMAL(10,2) NULL,
  `rua` VARCHAR(75) NULL,
  `localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  `contacto` VARCHAR(75) NULL,
  `responsavel` INT NOT NULL,
  `funcionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Familias_Elementos_idx` (`responsavel` ASC),
  INDEX `fk_Familias_Funcionarios1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_Familias_Elementos`
    FOREIGN KEY (`responsavel`)
    REFERENCES `mydb`.`Elementos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Familias_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Candidaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Candidaturas` (
  `id` INT NOT NULL,
  `dataAbertura` DATE NULL,
  `dataDecisao` DATE NULL,
  `observacoes` VARCHAR(75) NULL,
  `estado` VARCHAR(45) NULL,
  `funcionario` VARCHAR(45) NOT NULL,
  `familias` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Candidaturas_Funcionarios1_idx` (`funcionario` ASC),
  INDEX `fk_Candidaturas_Familias1_idx` (`familias` ASC),
  CONSTRAINT `fk_Candidaturas_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidaturas_Familias1`
    FOREIGN KEY (`familias`)
    REFERENCES `mydb`.`Familias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projectos` (
  `id` INT NOT NULL,
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  `estado` VARCHAR(45) NULL,
  `descricao` VARCHAR(75) NULL,
  `orcamento` DECIMAL(10,2) NULL,
  `funcionario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Projectos_Funcionarios1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_Projectos_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarefas` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectoTarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectoTarefas` (
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  `projecto` INT NOT NULL,
  `tarefas` INT NOT NULL,
  PRIMARY KEY (`projecto`, `tarefas`),
  CONSTRAINT `fk_ProjectoTarefas_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `mydb`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoTarefas_Tarefas1`
    FOREIGN KEY (`tarefas`)
    REFERENCES `mydb`.`Tarefas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voluntarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(75) NULL,
  `dataAssociacao` DATE NULL,
  `tipo` VARCHAR(45) NULL,
  `contacto` VARCHAR(75) NULL,
  `dataNascimento` DATE NULL,
  `profissao` VARCHAR(45) NULL,
  `rua` VARCHAR(75) NULL,
  `localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectoTarefaVoluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectoTarefaVoluntario` (
  `duracaoHoras` INT NULL,
  `dataRealizacao` DATE NULL,
  `voluntarios` INT NOT NULL,
  `tarefas` INT NOT NULL,
  `projecto` INT NOT NULL,
  PRIMARY KEY (`voluntarios`, `tarefas`, `projecto`),
  INDEX `fk_ProjectoTarefaVoluntario_Tarefas1_idx` (`tarefas` ASC),
  INDEX `fk_ProjectoTarefaVoluntario_Projectos1_idx` (`projecto` ASC),
  CONSTRAINT `fk_ProjectoTarefaVoluntario_Voluntarios1`
    FOREIGN KEY (`voluntarios`)
    REFERENCES `mydb`.`Voluntarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoTarefaVoluntario_Tarefas1`
    FOREIGN KEY (`tarefas`)
    REFERENCES `mydb`.`Tarefas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoTarefaVoluntario_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `mydb`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doadores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(75) NULL,
  `NIF` VARCHAR(45) NULL,
  `rua` VARCHAR(75) NULL,
  `Localidade` VARCHAR(75) NULL,
  `codPostal` VARCHAR(45) NULL,
  `contacto` VARCHAR(75) NULL,
  `dataAssociacao` DATE NULL,
  `actividade` VARCHAR(45) NULL,
  `email` VARCHAR(75) NULL,
  `site` VARCHAR(75) NULL,
  `pessoaDeContacto` VARCHAR(75) NULL,
  `Voluntarios_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Doadores_Voluntarios1_idx` (`Voluntarios_id` ASC),
  CONSTRAINT `fk_Doadores_Voluntarios1`
    FOREIGN KEY (`Voluntarios_id`)
    REFERENCES `mydb`.`Voluntarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `id` INT NOT NULL,
  `data` DATE NULL,
  `nrParticipantes` INT NULL,
  `observacoes` VARCHAR(75) NULL,
  `funcionario` VARCHAR(45) NULL,
  `projecto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Eventos_Funcionarios1_idx` (`funcionario` ASC),
  INDEX `fk_Eventos_Projectos1_idx` (`projecto` ASC),
  CONSTRAINT `fk_Eventos_Funcionarios1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `mydb`.`Funcionarios` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eventos_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `mydb`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doacoes` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(75) NULL,
  `data` DATE NULL,
  `tipo` VARCHAR(45) NULL,
  `valor` DECIMAL(10,2) NULL,
  `quantidade` INT NULL,
  `unidade` VARCHAR(45) NULL,
  `doador` INT NOT NULL,
  `evento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Doacoes_Doadores1_idx` (`doador` ASC),
  INDEX `fk_Doacoes_Eventos1_idx` (`evento` ASC),
  CONSTRAINT `fk_Doacoes_Doadores1`
    FOREIGN KEY (`doador`)
    REFERENCES `mydb`.`Doadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doacoes_Eventos1`
    FOREIGN KEY (`evento`)
    REFERENCES `mydb`.`Eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(75) NULL,
  `quantidade` INT NULL,
  `unidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectoMaterial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectoMaterial` (
  `quantidade` INT NULL,
  `material` INT NOT NULL,
  `projecto` INT NOT NULL,
  PRIMARY KEY (`material`, `projecto`),
  INDEX `fk_ProjectoMaterial_Projectos1_idx` (`projecto` ASC),
  CONSTRAINT `fk_ProjectoMaterial_Material1`
    FOREIGN KEY (`material`)
    REFERENCES `mydb`.`Material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectoMaterial_Projectos1`
    FOREIGN KEY (`projecto`)
    REFERENCES `mydb`.`Projectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
